appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} - [{i}, {T}, {I}] - [{h({l})}] (({t})) {m} (({M}, {f}, {L})){n}"

root:
  level: info
  appenders:
    - stdout

loggers:
  cfg_generator:
    level: info 
