/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.ncsu.lab.ast_tagger;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
    }
}
